### ISSUE TITLE
Derive Clone for GptDisk & mannual(fully customed) add_partition & pub partitions field

### ISSUE THREAD

**Issue by gaochuntie** [Quyzi/gpt#98]
There are two situation in my code: 
# (1)  
I am going to modify multi disk serially , so if any error occurs, I must revocer all thing.
I am going to do this by store unchanged disk instance to a list , if any error occus,just write all of them back.
## Problem : 
I can't push the disk instance into the list,nether the partitions field

`// part tabls backup , store orig part table in ram
    let mut tables_backup=HashMap::new();

    // move partition to target location
    for (part_name, raw_part) in &target_slot.dyn_partition_set {
        // store orig part table in ram
        let mut sector=LogicalBlockSize::Lb512;
        let sector_bytes= get_disk_sector_size(&raw_part.driver);
        if sector_bytes == 4096 {
            sector = LogicalBlockSize::Lb4096;
        } else if sector_bytes == 512 {} else {
            panic!("Error: unsupported sector size !!!");
        };
        let gptcfg = GptConfig::new().writable(true).logical_block_size(sector.clone());
        let mut disk = gptcfg.open(&raw_part.driver).expect("Error: open disk failed");
        //tables_backup.insert(raw_part.driver.clone(),disk.clone());
        // delete part by name
    };`

# (2) add_partition
I want to add a partition at a customed location , I will mannually compute all thing.
So I want a new add_partition func like gptfdisk do 
`   uint32_t CreatePartition(uint32_t partNum, uint64_t startSector, uint64_t endSector);`
But your func is also nice , just keep part_type and flag so the part I want is 
`pub fn add_partition(
        &mut self,
        name: &str,
        id: Option<u32>,
        size: Option<u64>,
        part_type: partition_types::Type,
        flags: u64,
        part_alignment: Option<u64>,
        first_lba: Option<u64>,
        last_lba: Option<u64>,
    ) -> Result<u32, GptError>`

**Comment by soerenmeier** [comment]
Hi, thanks for using gpt.

To start, please make sure you are using the latest version 4.0.0-rc.3 to which i will be referring.

You're right Clone was not implemented, it is now.
You might also find the [GptDisk::with_disk_device](https://docs.rs/gpt/4.0.0-rc.3/gpt/struct.GptDisk.html#method.with_disk_device) useful since `D` does not need to be cloneable.

You can add partitions with any values you want.
For this you need to modify the entire partition table [GptDisk::take_partitions](https://docs.rs/gpt/4.0.0-rc.3/gpt/struct.GptDisk.html#method.take_partitions).
Once you have updated the partitions you can set them again with [GptDisk::update_partitions](https://docs.rs/gpt/4.0.0-rc.3/gpt/struct.GptDisk.html#method.update_partitions).

**Comment by gaochuntie** [comment]
Ok,thank you for your hard-working. I was using 3.1 before,I will switch to the latest.
I found a fn: method gpt::header::Header::write_backup
Write the backup header.
But there is currently no load_backup .

**Comment by soerenmeier** [comment]
There are two functions to read a header other than GptDisk.
`gpt::header::read_header_from_arbitrary_device` and `gpt::header::read_header`
